name: Feature Request
description: Propose an enhancement or new feature for URDU-OCR-CNN
labels: ["enhancement"]
title: "[Feature]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out this form to help us understand your proposal.

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: Describe the problem or limitation you're experiencing
      placeholder: |
        Is your feature request related to a problem? Please describe.
        Example: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: |
        A clear and concise description of what you want to happen.
        Include any specific implementation details if you have them.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
      placeholder: |
        Describe any alternative solutions or features you've considered.
        Why would your proposed solution be better?
    validations:
      required: false

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Provide specific examples of how this feature would be used
      placeholder: |
        1. As a [type of user], I want to [do something] so that [benefit].
        2. When [scenario], this feature would help by [explanation].
      value: |
        1. 
        2. 
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the application would this feature affect?
      options:
        - Frontend (React/UI)
        - Backend (FastAPI/API)
        - Machine Learning (Model/Training)
        - Documentation
        - DevOps/Deployment
        - Multiple Components
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (Blocking current work)
        - High (Significant improvement)
        - Medium (Nice to have)
        - Low (Enhancement)
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: Define what should be included in this feature
      placeholder: |
        **In Scope:**
        - Feature A
        - Feature B
        
        **Out of Scope:**
        - Feature X (to be addressed separately)
    validations:
      required: false

  - type: textarea
    id: risks
    attributes:
      label: Potential Risks or Challenges
      description: Are there any potential risks or challenges with this feature?
      placeholder: |
        - Performance concerns
        - Breaking changes
        - Complexity
        - Dependencies
    validations:
      required: false

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: If applicable, add mockups, diagrams, or examples from other projects
      placeholder: Drag and drop images or paste URLs here...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, links, or references about the feature request
      placeholder: |
        - Related issues or PRs
        - External resources
        - Research or documentation
    validations:
      required: false

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation
      description: Would you be willing to help implement this feature?
      options:
        - label: I am willing to submit a pull request for this feature
          required: false
        - label: I can help with testing
          required: false
        - label: I can help with documentation
          required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: This feature aligns with the project's goals
          required: true
        - label: I have provided a clear description of the problem and solution
          required: true
